### ISSUE TITLE
Codebase: Ensure that Token Transfers are always the last actions in any transaction

### ISSUE THREAD

**Issue by matthiaszimmermann** [etherisc/gif-next#446]
Example: PolicyService.collateralize: instance.getInstanceStore().updatePolicy( is currently executed after token transfers which is not what we want

Steps
- [x] Identiry all token transfers in all services
- [x] Identify all transactions where token transfers are not the last actions
- [x] Fix those transactions
- [x] Decision: Event emit should also happen before transfer

**Comment by doerfli** [comment]
# ERC20 transfers (direct)

- [x] Component.setWallet 
- [ ] Switch `Component.setWallet` to use TokenHandler

# TokenHandler.safeTransferFrom()

- [x] not used by anyone

# TokenHandler.transfer()

- [ ] X DistributionService.withdrawCommission
- [ ] X BundleService.withdrawBundleFees
- [ ] X PoolService.unstake
- [ ] X PoolService.createBundle via _collectStakingAmount
- [ ] X PoolService.stake via _collectStakingAmount
- [ ] X ClaimService.processPayout via _transferPayoutAmount
- [ ] X PolicyService.collateralize via _processSaleAndTransferFunds
- [ ] X PolicyService.collectPremium via _processSaleAndTransferFunds
- [ ] X ComponentService.withdrawFees 
- [ ] X Staking.collectDipAmount
- [ ] X Staking.transferDipAmount

**Comment by rapidddenis** [comment]
Also we must not forget to check NFT tokens transfers too

**Comment by doerfli** [comment]
> Also we must not forget to check NFT tokens transfers too

Fair point. But i found no code that moves NFTs in our code. All NFTs are initially assigned to the correct owner. Transfer of NFT tokens seems to happen only outside of the framework so far. Please correct me if i am wrong.

**Comment by rapidddenis** [comment]
> > Also we must not forget to check NFT tokens transfers too
> 
> Fair point. But i found no code that moves NFTs in our code. All NFTs are initially assigned to the correct owner. Transfer of NFT tokens seems to happen only outside of the framework so far. Please correct me if i am wrong.

We have minting of NFTs which is transfer form 0 address (and soon will have burning)

**Comment by doerfli** [comment]
Actually i could not find code that moves nfts in our codebase. We mint directly to the address of the owner. But please correct me, since you've written most registry code, i think you know it better than me. 
Also i wonder: the NFT is a contract under our control (whereas ERC20 are most likely not), if that would not be a safe callout, then we would also have to ensure that for example all calls to InstanceStore would have to be only after internal state changing operations. So far i've treated call to contract that are deployed by us and the framework as safe to call.
