### ISSUE TITLE
Analyze Gas Consumption

### ISSUE THREAD

**Issue by matthiaszimmermann** [etherisc/gif-next#594]
- [ ] #653
- [x] #660 
- [x] #661
- [ ] #659

**Comment by doerfli** [comment]
create instance - https://amoy.polygonscan.com/tx/0x647f221b0ceab43b9738ecbbce4893866a8a822e0d17037feaeb3425a9950993
create bundle - https://amoy.polygonscan.com/tx/0x721253038b3024cd2f887200bae68fae84cb22a20921eeda02891ff47eee6d30

**Comment by doerfli** [comment]
# Deployment 30.8.2024

## Instance creation

https://amoy.polygonscan.com/tx/0x1b9c1917e67acca0eb7cfbe3a83c0ffab6ee7fcf2ad0b0ed21a0b246e9aed95b


## Component registration

product - https://amoy.polygonscan.com/tx/0x35ca630007f7f1073593a8717d0f5b7f663bbd37f82b789bec83c30a029193bf
pool - https://amoy.polygonscan.com/tx/0x02001c1218649bb3306ae1ce0803f44cb88b3db43b899f3f4f33f79cdfdafe1b

**Comment by doerfli** [comment]
# Analysis of the `create application` transaction

comparing the two transactions before and after the storage slot optimisation reveals almost no change in tx gas consumption. Further analysis revealed that the culprit is the `abi.encode(...)` in the KeyValueStore which pads each field to 32 bytes (https://medium.com/@scourgedev/deep-dive-into-abi-encode-types-padding-and-disassembly-84472f1b4543). So a crucial look at how to store the infos in necessary as currently storing costs a lot of gas. 

Also we think it might be worth trying to further gas optimize the authz methods. They are not expensive, but called often.
